### PR TITLE
gh actions with xapian wheels and caching

### PR DESCRIPTION
**Pull request by asedeno**
Updated with `xapian_wheel_builder.sh` and caching.

One outstanding question is this: `xapian_wheel_builder.sh` is used with a new flag `-t` which adds `xapian-delve` to the wheel. Should we make that unconditional, or let non-test wheels be that much slimmer?

### CODE REVIEW

**Comment by asedeno** [comment]
I'm going to make it unconditional. One less way to mess it up, and `xapian-delve` is already like 1% the size of `libxapian` so it's not a lot of overhead.

**Comment by asedeno** [comment]
Now all the tests pass too, though there is an issue with coverage stuff that I'm not looking into.

**Comment by claudep** [comment]
Thanks a lot! Coverage is not top priority for now, so if we don't find a solution now, we can deactivate it until later.

**Comment by asedeno** [comment]
It looks like the coveralls issue is an issue in the coveralls action itself.
https://github.com/coverallsapp/github-action/issues/30

**Comment by claudep** [comment]
Feel free to remove it until a solution is found.

**Comment by asedeno** [comment]
Let's try this. It doesn't work for me but I haven't tried to sign up for coveralls. Perhaps it'll work here or upstream?

**Comment by asedeno** [comment]
It works now.

**Comment by asedeno** [comment]
Well, kind of. It looks like some additional configuration is needed, but something will get uploaded to coveralls.

**Comment by asedeno** [comment]
It's actually working now. The last bit was obvious in retrospect.

**Comment by claudep** [comment]
Thanks a ton!! I squashed commits to let only two commits and pushed that on the master branch. Hopefully done right!

**Comment by asedeno** [comment]
Awesome. After that gets exercised some, we'll probably want to expand the test matrix.

**Pull request closed without merging**
